apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "basechart.name" . }}-worker
  labels:
    app: {{ template "basechart.name" . }}-worker
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $index, $index_value := .Values.worker.envValues }}
  {{ $index }}: {{ $index_value | quote }}
{{- end }}
