{{- if .Values.worker.flower.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "basechart.name" . }}-flower
  labels:
    app.kubernetes.io/name: {{ template "basechart.name" . }}-flower
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.dev.io/role: flower
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "basechart.name" . }}-flower
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.dev.io/role: flower
  replicas: {{ .Values.worker.flower.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "basechart.name" . }}-flower
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.dev.io/role: flower
    spec:
      # volumes:
      #   - name: static-assets
      #     configMap:
      #       name: {{ template "basechart.name" . }}
      #       defaultMode: 420
      containers:
        - name: {{ .Chart.Name }}-flower
          image: {{ .Values.worker.flower.image }}
          imagePullPolicy: {{ .Values.webapi.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "basechart.name" . }}
            - secretRef:
                name: {{ template "basechart.name" . }}
          ports:
            - containerPort: 5555
          # volumeMounts:
          #   - mountPath: /usr/share/nginx/html/
          #     name: static-assets
          cmd:
            - /bin/bash
            - -c
          args:
            - "flower"
            - "--port=5555"
            - "--broker=$(CELERY_BROKER_URL)"
          resources:
{{ toYaml .Values.webapi.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
{{- end }}