apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "basechart.name" . }}-scheduler
  labels:
    app.kubernetes.io/name: {{ include "basechart.name" . }}-scheduler
    helm.sh/chart: {{ include "basechart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.dev.io/role: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "basechart.name" . }}-scheduler
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.dev.io/role: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "basechart.name" . }}-scheduler
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.dev.io/role: scheduler
    spec:
      initContainers:
        - name: wait-for-redis
          image: {{ .Values.webapi.initContainerImage }}
          command:
            - 'sh'
            - '-c'
            - >
              until nc -z -w 2 {{ template "redis.hostname" . }} 6379 && echo redis ok;
                do sleep 2;
              done
      containers:
        - name: {{ .Chart.Name }}-scheduler
          image: {{ .Values.scheduler.image }}
          imagePullPolicy: {{ .Values.scheduler.pullPolicy }}
          cmd:
            - /bin/bash
            - -c
          args:
            {{- range .Values.scheduler.extraArgs }}
            - {{ . }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "basechart.name" . }}
            - secretRef:
                name: {{ template "basechart.name" . }}
          {{- if .Values.scheduler.probe }}
          livenessProbe:
            exec:
              # bash is needed to replace the environment variable
              command: [
                "/bin/bash",
                "-c",
                "celery inspect ping -A {{ .Values.scheduler.app.name }} -d celery@$HOSTNAME"
              ]
            initialDelaySeconds: 30  # startup takes some time
            periodSeconds: 60  # default is quite often and celery uses a lot cpu/ram then.
            timeoutSeconds: 10  # default is too low
          readinessProbe:
            exec:
              # bash is needed to replace the environment variable
              command: [
                "/bin/bash",
                "-c",
                "celery inspect ping -A {{ .Values.scheduler.app.name }} -d celery@$HOSTNAME"
              ]
            initialDelaySeconds: 30  # startup takes some time
            periodSeconds: 60  # default is quite often and celery uses a lot cpu/ram then.
            timeoutSeconds: 10  # default is too low
          {{- end }}
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}