apiVersion: v1
kind: Service
metadata:
  name: {{ template "basechart.name" . }}-web
  labels:
    app.kubernetes.io/name: {{ template "basechart.name" . }}-web
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.dev.io/role: web
spec:
  type: {{ .Values.webapi.service.type }}
  ports:
    - port: {{ .Values.webapi.service.externalPort }}
      targetPort: {{ .Values.webapi.service.internalPort }}
      protocol: TCP
      name: {{ .Values.webapi.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "basechart.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.dev.io/role: web
